stages:
- name: Build
  steps:
  - runScriptConfig:
      image: registry.gitlab.com/animocloud/rancher-pipeline-bootstrap:latest
      shellScript: |-
        # Get the ServiceAccount token from within the Pod's container
        # / TOKEN=$(cat /run/secrets/kubernetes.io/serviceaccount/token)# Call an API Server's endpoint (using the ClusterIP kubernetes service) to get all the Pods running in the default namespace
        # / curl -H "Authorization: Bearer $TOKEN" https://kubernetes/api/v1/namespaces/default/pods/ --insecure

        export PROJECT_TOKEN=$(cat /run/secrets/kubernetes.io/serviceaccount/token)
        export PROJECT_NAMESPACE=$(cat /run/secrets/kubernetes.io/serviceaccount/namespace)

        export BUILDPACK_URL=$(php -f buildpack-auth.php)

        env
        curl $BUILDPACK_URL -L -o buildpack.zip
        mkdir -p ./buildpack && unzip buildpack.zip -d ./buildpack
        mkdir -p ~/.ssh

        cp ./buildpack/keys/id_rsa ~/.ssh/id_rsa
        chmod 400 ~/.ssh/id_rsa
        cp ./buildpack/keys/id_rsa.pub ~/.ssh/id_rsa.pub
        chmod 400 ~/.ssh/id_rsa.pub
        chmod +x ./buildpack/scripts/system_build.sh
        ./buildpack/scripts/system_build.sh
- name: Publish image
  steps:
  - publishImageConfig:
      dockerfilePath: ./buildpack/docker/Dockerfile
      buildContext: .
      tag: ${CICD_GIT_REPO_NAME}/${CICD_PIPELINE_ID}:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: 127.0.0.1:30000
    env:
      PLUGIN_INSECURE: "true"
- name: Notifications
  steps:
  - runScriptConfig:
      image: registry.gitlab.com/animocloud/rancher-pipeline-bootstrap:latest
      shellScript: |-
        chmod +x ./buildpack/scripts/notify.sh
        ./buildpack/scripts/notify.sh
